version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  app:
    build: .
    container_name: 'app-invitation-manager'
    ports:
      - 3000:3000
      - 1080:1080
      - 1025:1025
      
    volumes:
      - .:/var/www
      - .bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    depends_on:
      - db

volumes:
  postgres_data:
